# Frigate Archive Manager

SOURCE="/media/frigate/recordings"
DEST="/mnt/truenas/frigate_archive/recordings"

LOGFILE="/opt/frigate-archive/logs/archive.log"
STATEFILE="/opt/frigate-archive/state/state.json"
LOCKFILE="/run/frigate-archive.lock"

# Kun færdige dato-mapper kopieres.
# Dagens mappe springes over.
VERIFY_COPY=true

# Home Assistant-notifikation sættes op senere.
HA_NOTIFY=false
HA_WEBHOOK_URL=""
HISTORYFILE="/opt/frigate-archive/state/history.json"
